services:
  mp_kasud:
    build: .
    image: mp_kasud_im:0.1
    ports:
      - 5000:5000
    volumes:
      - redis_volume:/data
      - ./src:/src
    environment:
      - REDIS_HOST=redis:6379
    #    healthcheck:
    #      test: ["CMD", "curl", "http://localhost:5000/"]
    #      interval: 20s
    #      retries: 5
    #      start_period: 5c
    depends_on:
      - redis
    networks:
      back:
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_volume:/data
    networks:
      back:
  db:
    container_name: my_db
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=pgpwd4habr
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8000
volumes:
  redis_volume:
networks:
  back:
